specVersion: 1.0.0
name: SubQuery Dictionary - ethereum
version: 1.0.0
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all
  projects
repository: "https://github.com/subquery/ethereum-dictionary"
schema:
  file: "./schema.graphql"

network:
  endpoint: wss://mainnet.infura.io/ws/v3/c3772903689441d290c68698bb022ba6
  # endpoint:  https://api.avax-test.network
  chainId: "1"
  subnet: "mainnet"

dataSources:
  - kind: ethereum/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: ethereum/BlockHandler
