specVersion: 1.0.0
name: SubQuery Dictionary - Avalanche
version: 1.0.0
runner:
  node:
    name: "@subql/node-avalanche"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all
  projects
repository: "https://github.com/subquery/avalanche-dictionary"
schema:
  file: "./schema.graphql"

network:
  endpoint: "avalanche.api.onfinality.io"
  port: 9650
  chainId: "mainnet"
  type: "avalanche"
  chainName: "C"

dataSources:
  - kind: avalanche/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: avalanche/BlockHandler
